context_description: "Les textes portent sur des incidents sur un réseau électrique."

competency_questions:
  - "Quels sont les événements survenus à une certaine date ?"
  - "De quoi est composé un événement ?"
  - "Quelles actions ont été implémentées sur le réseau sur ce créneau horaire [xx;yy] ?"
  - "Quels événements contextuels ont déclenché des événements réseau sur une certaine zone ?"

entity_types:
  - "Action"
  - "Border"
  - "CenterDivision"
  - "Client"
  - "Criticality_level"
  - "Datetime"
  - "Duration"
  - "Event"
  - "Event_impact"
  - "External_event"
  - "Location"
  - "PowerComponent"
  - "Power"
  - "Substation"
  - "Voltage"

entity_descriptions:
  Action: "Action menée par le gestionnaire du réseau électrique pour résoudre un problème."
  Border: "Indique un pays avec lequel a été effectuée une action à la frontière. L'entité ne désigne pas le pays en lui-même mais plutôt l'interface de la France avec ce pays."
  CenterDivision: "Nom du centre d'exploitation. Souvent le nom d'une grande ville française ou d'une région."
  Client: "Nom d'un client ou partenaire du gestionnaire du réseau."
  Criticality_level: "Indique la criticité ou non d'un événement réseau. Souvent, elle est portée par la présence d'un Message d'Importance Nationale (MIN)."
  Datetime: "Indique la temporalité d'une action, d'un événement. Il s'agit d'une heure mais pas d'une date. Est souvent indiquée en début de paragraphe."
  Duration: "Indique la durée de mise en œuvre d'une action ou d'un impact client (« pendant xx minutes » ou de « de xx h à yy h »)."
  Event: "Nom d'un événement pouvant survenir sur le réseau électrique."
  Event_impact: "Indique l'impact d'un événement réseau. Il peut s'agir de conséquences hors conséquences réseau (clients ou marché par exemple) liées à un événement."
  External_event: "Elément à l'origine de l'événement. Il peut s'agir d'un autre événement réseau, ou d'un incident externe (météo, demande du marché, ...)"
  Location: "La zone géographique constitue tout lieu qui ne représente pas une infrastructure ou une division du gestionnaire électrique. Il s'agit le plus souvent de villes, de régions, de pays."
  PowerComponent: "Fait référence à un élément d'infrastructure du gestionnaire de réseau électrique. Il peut s'agir de différents types d'objets : transformateurs, lignes, postes."
  Power: "Indique en puissance électrique la mise en oeuvre d'un levier/action, ou bien d'une conséquence d'un incident sur le réseau."
  Substation: "Poste électrique. Souvent écrit en majuscules."
  Voltage: "Caractérise une infrastructure (ex : liaison, poste). Décrit son niveau de tension intrinsèque."

relation_types:
  - "occuredAtTime"
  - "occuredAtPlace"
  - "hasOrigin"
  - "hasDuration"
  - "affectedComponent"
  - "impactedClient"
  - "of_electrical_power"
  - "has_nominal_value"

relation_descriptions:
  occuredAtTime: "Event --> Datetime"
  occuredAtPlace: "Event --> Location"
  hasOrigin: "Event --> External_event"
  hasDuration: "Event --> Duration"
  affectedComponent: "Event --> PowerComponent"
  impactedClient: "Event --> Client"
  of_electrical_power: "Event --> Power"
  has_nominal_value: "Substation --> Voltage"

entity_linker:
  action : "Action"
  border : "Border"
  center_division : "CenterDivision"
  client : "ThirdPartyActor"
  criticality_level : "CriticalityLevel"
  datetime : "Datetime"
  duration : "Duration"
  event : "Event"
  event_impact : "EventImpact"
  external_event : "OriginEvent"
  location : "GeographicalRegion"
  powercomponent : "PowerSystemComponent"
  power : "PowerFlow"
  substation : "Substation"
  voltage: "Voltage"
  other :   "Other"

additional_classes:
  - "Event"
  - "Action"
  - "Coupling"
  - "Disconnection"
  - "Incident"
  - "PowerOutage"
  - "OriginEvent"
  - "EventImpact"
  - "Location"
  - "Border"
  - "GeographicalRegion"
  - "CenterDivision"
  - "ThirdPartyActor"
  - "Datetime"
  - "Duration"
  - "PowerSystemComponent"
  - "Transformer"
  - "Line"
  - "Generator"
  - "Capacitor"
  - "Substation"
  - "Measurement"
  - "PowerFlow"
  - "Voltage"
  - "CriticalityLevel"

additional_properties:
  - name : "managed_by"
    domain : "PowerSystemComponent"
    range : "CenterDivision"
  - name : "has_nominal_value"
    domain : "PowerSystemComponent"
    range : "Voltage"
  - name : "located_in"
    domain : "PowerSystemComponent"
    range : "GeographicalRegion"
  - name : "handled_by"
    domain : "Incident"
    range : "CenterDivision"
  - name : "occured_on"
    domain : "Event"
    range : "PowerSystemComponent"
  - name : "occured_in"
    domain : "Event"
    range : "Substation"
  - name : "linked_to"
    domain : "Event"
    range : "Event"
  - name : "consequence_of"
    domain : "Event"
    range : "Event"
  - name : "similar_to"
    domain : "Event"
    range : "Event"
  - name : "solved_by"
    domain : "Incident"
    range : "Action"
  - name : "has_criticality"
    domain : "Incident"
    range : "CriticalityLevel"
  - name : "has_impact"
    domain : "Incident"
    range : "EventImpact"
  - name : "of_electrical_power"
    domain : "Event"
    range : "PowerFlow"
  - name : "of_voltage"
    domain : "Event"
    range : "Voltage"
  - name : "occured_at_datetime"
    domain : "Event"
    range : "Datetime"
  - name : "lasted_for"
    domain : "Event"
    range : "Duration"
  - name : "occured_in_place"
    domain : "Event"
    range : "GeographicalRegion"
  - name : "occured_at_border"
    domain : "Event"
    range : "Border"
  - name : "involved"
    domain : "Event"
    range : "ThirdPartyActor"
 